# Generated by Django 3.0.6 on 2020-09-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Numero Celular')),
                ('whatsapp', models.CharField(blank=True, max_length=10, verbose_name='WhatsApp')),
                ('address', models.CharField(max_length=20, verbose_name='Dirección')),
                ('correo', models.EmailField(blank=True, max_length=50, verbose_name='E-mail')),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
    ]
