# Generated by Django 3.0.6 on 2020-09-09 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='phone_number',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='first_name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='address',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('0', 'Cliente'), ('1', 'Negocio')], default='0', max_length=1, null=True),
        ),
    ]
