# Generated by Django 3.0.6 on 2020-09-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200908_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Negocio', 'Negocio')], default='0', max_length=7, null=True),
        ),
    ]
