# Generated by Django 3.0.4 on 2020-09-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20200909_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='hombre', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Negocio', 'Negocio')], default='cliente', max_length=7, null=True),
        ),
    ]
