# Generated by Django 3.0.6 on 2020-09-08 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_out', models.DateField(blank=True, null=True, verbose_name='Fecha Salida')),
                ('imei', models.CharField(blank=True, max_length=15, verbose_name='Imei')),
                ('modelo', models.CharField(choices=[('0', 'iPhone-SE'), ('1', 'iPhone-6'), ('2', 'iPhone-6+'), ('3', 'iPhone-6S'), ('4', 'iPhone-6S+'), ('5', 'iPhone-7'), ('6', 'iPhone-7+'), ('7', 'iPhone-8'), ('8', 'iPhone-8+'), ('9', 'iPhone-X'), ('10', 'iPhone-XR'), ('11', 'iPhone-XS'), ('12', 'iPhone-XS+'), ('13', 'iPhone-11'), ('14', 'iPhone-11PRO'), ('15', 'iPhone-11PRO+'), ('16', 'Otro')], max_length=2, null=True, verbose_name='Modelo')),
                ('contraseña', models.CharField(blank=True, max_length=6, null=True, verbose_name='Contraseña')),
                ('falla', models.TextField(null=True, verbose_name='Falla')),
                ('accesorios', models.CharField(blank=True, choices=[('0', 'Si'), ('1', 'No')], max_length=1, null=True)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('reparado', models.CharField(blank=True, choices=[('0', 'Si'), ('1', 'No')], max_length=1, verbose_name='Reparado')),
                ('solucion', models.TextField(blank=True, null=True, verbose_name='Solucion')),
                ('estado', models.CharField(choices=[('0', 'Recibido'), ('1', 'En reparación'), ('2', 'Reparado'), ('3', 'No Reparado'), ('4', 'Entregado'), ('5', 'Garantía')], default='Recibido', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'ordering': ['-id'],
            },
        ),
    ]
