# Generated by Django 3.0.4 on 2020-09-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_auto_20200908_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cobro',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnostico'),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_out',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Salida'),
        ),
        migrations.AddField(
            model_name='orden',
            name='gasto',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='medio_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Debe', 'Debe')], default='Efectivo', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='reparacion',
            field=models.TextField(blank=True, null=True, verbose_name='Reparacion'),
        ),
        migrations.AddField(
            model_name='orden',
            name='reparado',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Reparado'),
        ),
        migrations.AddField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='accesorios',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('En reparación', 'En reparación'), ('Reparado', 'Reparado'), ('No Reparado', 'No Reparado'), ('Entregado', 'Entregado'), ('Garantía', 'Garantía')], default='Recibido', max_length=15),
        ),
        migrations.AlterField(
            model_name='orden',
            name='modelo',
            field=models.CharField(choices=[('iPhone-SE', 'iPhone-SE'), ('iPhone-6', 'iPhone-6'), ('iPhone-6+', 'iPhone-6+'), ('iPhone-6S', 'iPhone-6S'), ('iPhone-6S+', 'iPhone-6S+'), ('iPhone-7', 'iPhone-7'), ('iPhone-7+', 'iPhone-7+'), ('iPhone-8', 'iPhone-8'), ('iPhone-8+', 'iPhone-8+'), ('iPhone-X', 'iPhone-X'), ('iPhone-XR', 'iPhone-XR'), ('iPhone-XS', 'iPhone-XS'), ('iPhone-XS+', 'iPhone-XS+'), ('iPhone-11', 'iPhone-11'), ('iPhone-11PRO', 'iPhone-11PRO'), ('iPhone-11PRO+', 'iPhone-11PRO+'), ('Otro', 'Otro')], max_length=20, null=True, verbose_name='Modelo'),
        ),
    ]
