# Generated by Django 3.0.6 on 2020-09-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='medio_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Debe', 'Debe')], default='Efectivo', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='reparado',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Reparado'),
        ),
    ]
